---
title: "Presentation details"
---

Aurel Wünsch and Sam Herniman will be talking at [Fluconf](https://2026.fluconf.online/) about [indoorco2map.com](https://indoorco2map.com/?lat=51.16570&lng=10.45150&zoom=6.00), a community science project to measure indoor CO~2~ around the world.

## Details

Date: [2026-02-01 18:00 UTC+0](https://time.is/1800_1_Feb_2026_in_London?Fluconf_-_IndoorCO2)  
Location: [Youtube Live](https://www.youtube.com/@aurelwu/live)

## If you missed us
You can watch the recording [here](https://www.youtube.com/watch?v=60YwSH9g3Bg)

## Speakers

Aurel Wünsch specializes in electricity markets, energy scenarios and sector coupling. In his free time, Aurel, created indoorco2map.com – an open source citizen science project mapping indoor air quality worldwide.  
[Github](https://github.com/AurelWu) [Bluesky](https://bsky.app/profile/aurel.indoorco2map.com)

Sam is a spatial data scientist specializing in quantitative ecology and community science. Sam is a long time volunteer with indoorco2map.com.  
[Github](https://github.com/samherniman) [Website](https://sam.rbind.io/) [Fediverse](https://fosstodon.org/@samherniman)

## Abstract
There is a well documented relationship between indoor levels of CO~2~ and the amount of ventilation in indoor environments. Buildings with high indoor levels of CO~2~ have poor ventilation and are therefore more likely to be vectors of airborne diseases (like COVID-19, Measles, and Flu) and to trap indoor pollutants. High CO~2~ levels are also correlated with headaches, dizzyness and lower mental performance.  

Measuring CO~2~ inside is a really cheap way of measuring the air quality in indoor environments. When we breathe, we exhale  CO~2~ and it gets trapped inside the room we are in. If the building has good ventilation it will leave quickly. If it has bad ventilation, it stays in the room and builds up. CO~2~ levels outside are typically around 423 parts per million (ppm), if we measure the CO~2~ in a room and it is higher than that, we can measure how ventilated the room is.

If there is bad ventilation, then smoke from cooking can build up and that's bad for you. Same thing for VOCs from perfumes, as well as gas leaks, radon, and mold spores. At high concentrations in artificial environments, they contribute to all sorts of things: cancer, Alzheimer's, Parkinson's, childhood asthma, childhood lung problems, and heart conditions.
Bad ventilation also contributes to a much higher risk of respiratory infections. If someone who is sick breathes in a badly ventilated room, the infectious aerosols will float around in the room until someone breathes them in. In a well ventilated space, they are dispersed very quickly and the risk of infection is much lower. Having an open window in a classroom (or having an air filter), for instance, reduces school absences significantly.

[Indoor CO2-Map](https://indoorco2map.com) is an open source community science project to monitor indoor CO~2~ levels in non-residential buildings and transit systems around the world. Since April 2024 volunteers have brought CO~2~ monitors into cafes, shops, schools, trains, and all sorts of other places to monitor CO~2~ levels in them and upload them to a public database. In this presentation, we illustrate how this project was built, summarise recent findings, and detail how you can be involved!